sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "8"
before_install:
  - npm install -g bower
  - bower install
script:
  - npm run lint
  - npm run test-coverage
  - npm run test-integration
cache:
  directories:
  - node_modules
