sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "8"
before_install:
  - npm install -g bower
  - npm i -g npm@^5
  - bower install
script:
  - make ci
cache:
  directories:
  - node_modules
